### ISSUE TITLE
Networking blocked by sandbox on Linux and Mac

### ISSUE THREAD

**Issue by sammacbeth** [cliqz-oss/dat-webext#11]
The firefox process sandbox prevents opening of sockets from the content process. We should run the networking on addon parent scope to avoid this. This will need a refactor of the libdweb implementations of `TCPSocket` and `UDPSocket`.

**Comment by sammacbeth** [comment]
I put together an implementation of the `TCPSocket` which runs in the parent scope, and that seems to fix the API. Just need to do the same for `UDPSocket` then this should be resolved.

libdweb branch with the current progress: https://github.com/sammacbeth/libdweb/tree/tcp-parent

**Comment by RangerMauve** [comment]
Oh HELL yeah! :D

Will that mean support for dat-webext in Cliqz on Linux and Mac? :D

**Comment by sammacbeth** [comment]
`UDPSocket` implementation is now also done. I pushed a new build and this fixes the issue now on both Mac and Linux.
