### ISSUE TITLE
No affordance to enable dat:// protocol after installing in FFx Nightly

### ISSUE THREAD

**Issue by emceeaich** [cliqz-oss/dat-webext#112]
After building the extension, making the changes to sandbox, and installing it, I see these options:

![image](https://user-images.githubusercontent.com/10146300/76490441-64078b80-63e8-11ea-8b9b-697412814505.png)

FFx 76 Nightly on Ubuntu 19.10 (wayland)

But I don't see an option to enable the dat:// protocol. 

Is this related to the issues on Mac and Linux mentioned in the blog post?

**Comment by sammacbeth** [comment]
The enable checkbox in Cliqz just does an extension enable/disable. If you are running in Firefox then the protocol should work once you load the extension. You may be missing the `extensions.experiments.enabled` pref, which needs to be set to true to enable the libdweb apis. This was added to Firefox a couple of versions ago, so the current readme is out-of-date.

**Comment by emceeaich** [comment]
Excellent. I enabled that preference and now I'm able to use dat://. 

I'll submit a PR for the README.
