### ISSUE TITLE
Protocol handler doesn't seem to be running

### ISSUE THREAD

**Issue by RangerMauve** [cliqz-oss/dat-webext#20]
Hey, I tried to run the extension with Firefox Nightly, and it seems to be getting loaded, but when I navigate to a `dat://` URL, it prompts me to open Beaker rather than trying to load it in Firefox.

I'm on Windows 10 with dat-webext 0.0.8 and Firefox Nightly 69.0a1

**Comment by sammacbeth** [comment]
The extension requires the browser sandbox to be disabled in order to be loaded. You can do that either by using the `web-ext` launcher (via `npm run start`), or by setting the `security.sandbox.content.level pref` pref to `2` as described in the readme (requires browser restart afterwards).

**Comment by RangerMauve** [comment]
I ran it with web-ext and got the above result. 😅 I could try adding the flag, too, though. Would nightly be different from developer edition?

**Comment by RangerMauve** [comment]
Deleteing and reinstalling node_modules fixed it!
