### ISSUE TITLE
datPeers support

### ISSUE THREAD

**Issue by RangerMauve** [cliqz-oss/dat-webext#21]
I've been experimenting with the [datPeers](https://beakerbrowser.com/docs/apis/experimental-datpeers) API in Beaker for [P2P multiplayer](https://github.com/RangerMauve/aframe-dat-peers-networking) in VR. It'd be cool if dat-webext could support this functionality since it'd enable some fancy mobile use-cases.

A really exciting prospect would be loading the extension into [Firefox Reality](https://github.com/MozillaReality/FirefoxReality/issues/299) and getting P2P WebXR for free. :D

**Comment by sammacbeth** [comment]
I'm waiting for the ideas around this API to stabilize before I look at implementing it. That said, if someone wants to look at implementing it, I'd be happy to point out how this could be done.

**Comment by RangerMauve** [comment]
I started working on an [implementation](https://github.com/RangerMauve/dat-peers) that works by having you pass an archive to it. So once that's ready it'll probably *Just Work™* in dat-webext

**Comment by RangerMauve** [comment]
datPeers is dead. There's a new peersockets thing, but I think we should think about API stuff some more. 🤷
