### ISSUE TITLE
I would like to use the latest addOn version with the Cliqz browser

### ISSUE THREAD

**Issue by pmario** [cliqz-oss/dat-webext#54]
I would like to use the latest addOn version with the Cliqz browser.

The [release page](https://github.com/cliqz-oss/dat-webext/releases) doesn't contain a signed .xpi, that could be used with FF nightly or the latest cliqz-browser. 

How can I use latest addOn with latest cliqz beta channel?

**Comment by sammacbeth** [comment]
The Cliqz beta channel should automatically get the latest version (0.0.13). You can check this in the `about:support` page, under 'Cliqz Features'. It should look like the following:
![Screenshot 2019-09-05 at 13 55 54](https://user-images.githubusercontent.com/248111/64339755-fe73b600-cfe4-11e9-9c20-cb19e5d31c2f.png)

The XPI can also be directly downloaded here: https://s3.amazonaws.com/cdncliqz/update/browser_pre/dat%40cliqz.com/dat%40cliqz.com-0.0.13-browser-signed.xpi
I tested this, and could successfully load the extension in the Cliqz release build and Firefox developer edition, but not in Nightly.

I'll update the readme to include the signed XPI for Firefox users who want to try it out.

**Comment by pmario** [comment]
Thx for the info. I did have a look at `about:debugging` and the plugin didn't show any additional info, so I couldn't see the manifest. ... Today everything is shown just fine. That's strange. 

closing for now!
